baseURL = "//brainhack-proceedings.github.io/template/"
languageCode = "en-us"
title = "BrainHack 2020"
publishdir = "public"
theme = "business-frontpage"

[params]
    author = "OHBM Brainhack 2020"
    description = "Proceeding page."

    [params.navbar]
    about = "About"
    about_url = "#"
    papers = "Papers"
    papers_url = "https://brainhack-proceedings.github.io/papers"
    blog = "Blog"
    blog_url = "https://brainhack-proceedings.github.io/blog"
    submit = "Submit"
    submit_url = "https://github.com/brainhack-proceedings/submit"

    [[params.navbar.nav]]
    current = true
    name = "OHBM Hackathon 2020"
    url = "https://ohbm.github.io/hackathon2020/"

    [params.header]
    name = "Business Name or Tagline"
    tagline = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non possimus ab labore provident mollitia. Id assumenda voluptate earum corporis facere quibusdam quisquam iste ipsa cumque unde nisi, totam quas ipsam."

    [params.footer]
        copyright = "BrainHack"